# Generated by Django 4.1.13 on 2024-11-22 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='description',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='players',
        ),
    ]
