# Generated by Django 4.1.13 on 2025-04-06 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments_app', '0002_remove_tournament_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
