# Generated by Django 4.1.13 on 2025-04-06 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments_app', '0003_alter_tournament_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='tournament_tree',
            field=models.JSONField(default=dict),
        ),
    ]
