# Generated by Django 4.1.13 on 2025-04-07 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments_app', '0005_participant_tournament_champion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='champion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_tournaments', to='tournaments_app.participant'),
        ),
    ]
