# Generated by Django 4.1.13 on 2025-04-07 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments_app', '0006_alter_tournament_champion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='user_id',
            field=models.IntegerField(),
        ),
    ]
