# Generated by Django 5.1.5 on 2025-02-28 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left_player_id', models.IntegerField()),
                ('left_player_username', models.CharField(max_length=100)),
                ('left_player_score', models.IntegerField(default=0)),
                ('right_player_id', models.IntegerField()),
                ('right_player_username', models.CharField(max_length=100)),
                ('right_player_score', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_finished', models.BooleanField(default=False)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('winner_username', models.CharField(blank=True, max_length=100, null=True)),
                ('tournament_id', models.IntegerField(default=0)),
                ('tree_index', models.IntegerField(default=0)),
                ('rock_paper_scissors_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RockPaperScissorsGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left_player_id', models.IntegerField()),
                ('left_player_username', models.CharField(max_length=100)),
                ('left_player_choice', models.CharField(default='', max_length=100)),
                ('right_player_id', models.IntegerField()),
                ('right_player_username', models.CharField(max_length=100)),
                ('right_player_choice', models.CharField(default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_finished', models.BooleanField(default=False)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('winner_username', models.CharField(blank=True, max_length=100, null=True)),
                ('tournament_id', models.IntegerField(default=0)),
                ('tree_index', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
