# Generated by Django 5.1.5 on 2025-01-22 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='return_url',
            field=models.URLField(default=''),
        ),
    ]
