# Generated by Django 5.1.5 on 2025-02-28 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='return_url',
        ),
        migrations.RemoveField(
            model_name='rockpaperscissorsgame',
            name='return_url',
        ),
        migrations.AlterField(
            model_name='game',
            name='tournament_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='game',
            name='tree_index',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rockpaperscissorsgame',
            name='tournament_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rockpaperscissorsgame',
            name='tree_index',
            field=models.IntegerField(default=0),
        ),
    ]
