# Generated by Django 5.1.5 on 2025-02-01 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_app', '0002_game_return_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_id',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='game',
            name='tournament_id',
            field=models.IntegerField(default=0),
        ),
    ]
