# Generated by Django 5.1.5 on 2025-02-10 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_app', '0003_game_game_id_game_tournament_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='tournament_id',
            field=models.CharField(default='', max_length=100),
        ),
    ]
