# Generated by Django 5.1.5 on 2025-02-08 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_app', '0003_game_game_id_game_tournament_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='game_id',
            new_name='tree_id',
        ),
    ]
