# Generated by Django 5.1.5 on 2025-02-19 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_app', '0005_rename_game_id_game_tree_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='RockPaperScissorsGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left_player_id', models.IntegerField()),
                ('left_player_username', models.CharField(max_length=100)),
                ('left_player_choice', models.CharField(default='', max_length=100)),
                ('right_player_id', models.IntegerField()),
                ('right_player_username', models.CharField(max_length=100)),
                ('right_player_choice', models.CharField(default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_finished', models.BooleanField(default=False)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('winner_id', models.IntegerField(blank=True, null=True)),
                ('return_url', models.URLField(default='')),
                ('tournament_id', models.CharField(default='', max_length=100)),
                ('tree_index', models.CharField(default='', max_length=100)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='game',
            name='rock_paper_scissors_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='winner_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
