# Generated by Django 5.1.5 on 2025-02-19 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_app', '0006_rockpaperscissorsgame_game_rock_paper_scissors_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='winner_id',
        ),
        migrations.RemoveField(
            model_name='rockpaperscissorsgame',
            name='winner_id',
        ),
        migrations.AddField(
            model_name='game',
            name='winner_username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rockpaperscissorsgame',
            name='winner_username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
