# Generated by Django 5.1.5 on 2025-02-28 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_app', '0004_rename_game_id_game_tree_id'),
        ('game_app', '0007_remove_game_winner_id_and_more'),
    ]

    operations = [
    ]
