# Generated by Django 4.1.13 on 2025-04-09 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.CharField(blank=True, default='/media/default0.gif', max_length=255, null=True),
        ),
    ]
