# Generated by Django 4.1.13 on 2025-04-21 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0005_alter_customuser_email_alter_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(error_messages={'blank': 'El nombre de usuario no puede estar vacío', 'max_length': 'El nombre de usuario no puede tener más de 20 caracteres', 'unique': 'Ya existe un usuario con este nombre'}, max_length=20, unique=True, verbose_name='username'),
        ),
    ]
